

---
# local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/ridingmate?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
cloud:
  aws:
    s3:
      bucket : ridingmate-test
    region:
      static: ap-northeast-2

server:
  port: 8080
  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
    whitelabel.enabled: true


